### ISSUE TITLE
Tavern '1.0' changes

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#119]
There are a few things that need changing and a few issues open that are hard to fix without breaking backwards compatibility. To make sure we know what is going to break in advance, I'm going to try and lay it all out here. This is almost all just related to tighter integration with pytest.

### pytest integration

- `tavern-ci` will either be removed or just become an alias for `py.test`
- A 'base' REST/MQTT request/response object to make it easier for plugins to verify responses

- `delay_after` and `delay_before` will become built-in fixtures or hooks. This is a breaking API change.
- parametrization with pytest - running the same test, but with a different formatted value (or possibly a different dict/list/value)
- marking tests - this will just be for use with the `-m` flag. A list of tags applied to each test which can be used to run a certain subset of tests.
- This is sort of covered by parametrization and fixtures, but we want to be able to add 'plugin' blocks depending on a fixture. eg https://github.com/taverntesting/tavern/issues/113 . This would probably be a breaking API change, but I doubt many people are using plugins at the moment so it shouldn't be too bad.

Either/both:
- Some sort of integration with pytest fixtures - unsure how this will work now, but it will allow you to do some arbitrary python code and return a dictionary/list/value for the request/response/etc. This will probably be implemented such that we can `send` a value to the fixture if it's a generator, so fixtures can be written like this:
```python
@pytest.fixture(name="tavern_complicated_request_val")
def test_complicated_return_value():
    val = calculate_something_complicated()

    response = (yield val)

    expected = calculate_complicated_response()
    assert response.body["value"] == expected    
```
```yaml
request:
  json:
    sent_value: !fromfixture "tavern_complicated_request_val"
```
- extra hooks to allow people to run things before/after/during tests. For example, a hook called `tavern_before_test` which is run before every test and is called with the associated `request` and `YamlItem`.

Either one of these should cover all use cases, but both of them being available would definitely be the best case scenario.

### Possible

- xfailing tests - this is probably going to be hidden from external use but it would be helpful to be able to write a deliberately broken test for tavern to make sure that it can be caught and reported to the user appropriately.
- skipif with pytest - eg, skip a test if running against a certain server. This will provide similar but different functionality to marking tests. I'm not sure of a nice way to implement this other than using `exec()`, but that might just have to happen.

### problems

- Pytest only has the concept of a test, not the concept of a stage like Tavern does. We don't want to have to reimplement all the possible pytest behaviour for stages as well as tests, so adding parametrization or marking to individual stages is probably not going to happen. skip/skipif should be possible. Fixtures will almost always have to be run per-stage, so there may be some rudimentary 'decoration' of stages and tests to allow for this.

### Note going to happen as a part of 1.0

- Better test reporting - this is quite a lot of work, but adding a better error reporting which actually prints the stage that failed and why it failed with arrows next to it like pytest would help a lot.

Note that **none of this is set in stone**, and no schema for the above changes has been decided on. This probably isn't going to be pushed out for at least a month or two. If there are any other (minor) breaking API changes that would greatly improve the user experience, feel free to suggest them here.

**Comment by michaelboulton** [comment]
Another thing will be fixing the comparison of keys at the top level. If a server returns this:

```json
{
  "a": "b",
  "c": 4,
}
```

then it will not raise an error if the tavern test is like this:

```yaml
response:
  body:
    a: b
```

because it won't check for the 'c' key. This will be fixed so that it will always check all keys.

This could be done before 1.0 by having an extra option either globally, per test, or per stage to 

1. use legacy behaviour (default, logs warning, removed in 1.0)
2. ignore extra keys in response, at all levels
2. strict behaviour, where everything must match

**Comment by michaelboulton** [comment]
Also `null` checking will be removed in favour of using `!anything`, `!anystr`, etc.

**Comment by michaelboulton** [comment]
There will probably be some changes to the 'meta' block as well

**Comment by michaelboulton** [comment]
The `run()` entry point will have all arguments except the `in_file` removed

as per https://github.com/taverntesting/tavern/issues/127#issuecomment-398409023

**Comment by benhowes** [comment]
The new error formatting from https://github.com/taverntesting/tavern/pull/134 will become default

**Comment by michaelboulton** [comment]
If we can get per-stage before/after hooks or fixtures  working nicely  then we might remove the `$ext` blocks as well

**Comment by michaelboulton** [comment]
A minor thing, but #138 reminded me that I was going to switch from using the `recursive_key_access` function to using jmespath. this is a breaking changes because it would change things like `a.b.0.c` to `a.b[0].c`

**Comment by benhowes** [comment]
@michaelboulton shall we get the 1.0 release out by the end of August?

**Comment by michaelboulton** [comment]
I will make a branch with some of the breaking changes in it soon, I think we can implement a lot of this stuff but a couple of weeks might be too short between making the breaking changes and releasing it

Things that need changing in 1.0 branch

- [ ] https://github.com/taverntesting/tavern/issues/119#issuecomment-404187238 Changing to use jmespath
- [ ] https://github.com/taverntesting/tavern/issues/119#issuecomment-398409218 just removing the tavern_global_cfg from the call - moved to either pytest config or passed in as a pytest_args variable.
- [ ] https://github.com/taverntesting/tavern/issues/119#issuecomment-399098198 make new traceback default. This seems to work fine for now, there will still be a flag saying 'use the default pytest style tracebacks'
- [ ] https://github.com/taverntesting/tavern/issues/119#issuecomment-396550268 remove 'null' matching anything
- [ ] https://github.com/taverntesting/tavern/issues/119#issuecomment-396519348 make either strict or non strict key checking the default. Not sure which is better as a 'default'

Not doing

- https://github.com/taverntesting/tavern/issues/119#issuecomment-402487413 per-stage fixtures. This could be done in future, but reimplementing the Pytest stuff would be too complicated and take too long

**Comment by michaelboulton** [comment]
Remove `body` key in response, change to `json`. This maintains parity with the mqtt side (and the request syntax) and makes it explicit that it will only check json

**Comment by michaelboulton** [comment]
Drop python 2 support

**Comment by michaelboulton** [comment]
https://github.com/taverntesting/tavern/issues/495
